trigger:
- main

pr:
- '*'

variables:
- name: BUILD_NUMBER
  value: $[counter('buildnumber', 200)]

jobs:
- job: Windows
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-latest
      MacOS:
        vmImage: macOS-latest
      Windows:
        vmImage: windows-latest
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      version: '3.1.x'
      packageType: sdk
  - task: UseDotNet@2
    displayName: Install .NET Core 2.1 runtime
    inputs:
      version: '2.1.x'
      packageType: runtime
  - task: NodeTool@0
    displayName: Install NodeJS 12.x
    inputs:
      versionSpec: 12.x
  - powershell: ./build.ps1 -ci
    displayName: Invoke build.ps1
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: $(vmImage)
      testRunner: vstest
      testResultsFiles: '**/*.trx'
  - publish: artifacts/
    artifact: Packages
    displayName: Publish artifacts
    condition: and(succeeded(), eq('windows-latest', variables['vmImage']))
